spring.datasource.url=jdbc:postgresql://localhost:5432/saas_pos
spring.datasource.username=postgres
spring.datasource.password=vishal@3932

# IMPORTANT
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANT
spring.flyway.enabled=false