spring.datasource.url=jdbc:postgresql://localhost:5432/saas_pos
spring.datasource.username=postgres
spring.datasource.password=vishal@3932

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false

jwt.secret=myVeryStrongJwtSecretKeyForNextGenPos123456789
jwt.expiration=180000
jwt.refresh.expiration=604800000

# LOG FILE
logging.file.name=logs/app.log

# Max file size
logging.logback.rollingpolicy.max-file-size=10MB

# Keep old logs
logging.logback.rollingpolicy.max-history=7

# Total size limit
logging.logback.rollingpolicy.total-size-cap=100MB

# RAZORPAY (TEST KEYS) - replace with your test keys
razorpay.key.id=rzp_test_SutuJ4LOVKGUJP

razorpay.key.secret=0l7Iherld9Mjn4u6oTZ9eWOh

stock.low.limit=20